spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # for dev, use 'validate' or migrations in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: keerthipriya014@gmail.com
    password: pikr icfb zauo pwha
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: 8090

jwt:
  secret: verySecretKeyChangeInProd
  expiration: 86400000 # 24 hours in ms

logging:
  level:
    org.springframework: INFO
